url: http://www.linnullmann.no
sitename: 'Linn Ullmann'
description: 'Linn Ullmann is an award winning novelist and journalist and the author of five novels: Before You Sleep, Stella Descending, Grace, A Blessed Child and The Cold Song.'
# do not include  https://github.com/...
repo: 'sonnetmedia/linnullmann'
branch: gh-pages
default_author: "Bud Parr"

#Jekyll Options
# if using more than one Jekyll instance on your local machine
port: 3575
# paginate tells Jekyll how many posts per page
# paginate: 1
# Permalinks
permalink:  pretty
# Dependencies
# markdown: kramdown
# pygments: true
#Pages - store all pages in the _pages directory
include: ['_pages']
# relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'package.json', 'gruntfile.js', 'Gemfile.lock', 'gemfile']

# dev options (true/false)
# if site is in production, 'production: true'
production: true
use_pure_css: false
use_jquery_cdn: true
include_font_awesome: false
include_addthis_sharing: false

# options (data)
google_analytics_id: UA-365683-21
disqus_id:
addthis_id:
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:

# options (social)
# facebook_id:
twitter_id:
