# jekyll-seo-tag
title: "Linn Ullmann"
sitename: 'Linn Ullmann' #old
description: 'Linn Ullmann is an award winning novelist and journalist and the author of five novels: Before You Sleep, Stella Descending, Grace, A Blessed Child and The Cold Song.'
url: "https://www.linnullmann.no" # the base hostname & protocol for your site
author: []
twitter:
  username:
facebook:
  app_id:
  publisher:
  admins:
logo: /uploads/2015-ullmann-de-urolige-500px.jpg
google_site_verification:
github:
  username: budparr
owner: Linn Ullman
# manifest
short_name: Linn Ullman
display: fullscreen

gems:
  - jekyll-seo-tag

plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

languages:
  - english
  - norsk
categories:
  - News
# Permalinks
permalink:  pretty

include:
  - _pages
exclude:
  - readme.md
  - license.md
  - Gemfile
  - links.jsonp
  - CNAME
  - rakefile
  - bower.json
  - node_modules
  - package.json
  - gruntfile.js
  - Gemfile.lock
  - gemfile
  - Gruntfile.js
  - notes.md


# dev options (true/false)
# if site is in production, 'production: true'
production: true
include_addthis_sharing: false

# options (data)
google_analytics_id: UA-365683-21


# CONTENT
collections:
  en_landing_pages:
    output: true
    permalink: '/:path/'
  no_landing_pages:
    output: true
    permalink: '/:path/'
  en_books:
    output: true
    permalink: '/en/books/:path/'
  no_books:
    output: true
    permalink: '/boker/:path/'
  reviews:
    output: false
    _comments:
      title: "The Source of the Review Quote. Use an asterisk around a word to italicize it."



_comments:
   permalink: 'permalink looks like: /link-name/'
   no_landing_page: 'choose the alternative language version of this page'
   en_landing_page: 'choose the alternative language version of this page'
defaults:
  - scope:
      path: ''
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'en_landing_pages'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'no_landing_pages'
    values:
      layout: page-single
  - scope:
      path: ''
      type: en_books
    values:
      layout: book
  - scope:
      path: ''
      type: no_books
    values:
      layout: book
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      schema: BlogPosting
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      schema: BlogPosting
